name: Capsule

on:
  push: {}
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Dependencies
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
          cargo install --locked ckb-capsule
      - name: Build
        run: capsule build
      - name: Run tests
        run: capsule test
      - name: Build Release
        run: capsule build --release

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ckb-sdk-examples-capacity-diff
