name: Capsule

on:
  push: {}
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Dependencies
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
          cargo install --locked ckb-capsule
      - name: Build
        run: capsule build
      - name: Run tests
        run: capsule test
      - name: Build Release
        run: capsule build --release && ls -lR target
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ckb-sdk-examples-capacity-diff
          path: target/riscv64imac-unknown-none-elf/release/ckb-sdk-examples-capacity-diff

  release:
    needs: build-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ckb-sdk-examples-capacity-diff
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ckb-sdk-examples-capacity-diff
